### ISSUE TITLE
Síntesis Buenas Practicas en Gestión de Proyectos de Software 

### ISSUE THREAD

**Issue by garaudy12** [SistemasTecTlaxiaco/sintesis-garaudy12#2]
[Sintesís Taolí Garaudy Solano Mendoza.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-garaudy12/files/7151131/Sintesis.Taoli.Garaudy.Solano.Mendoza.pdf)

**Comment by Jaimer117** [comment]
calificación 20%

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
